# permissions for end users to view netboxippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-ipam-provider-netbox
    app.kubernetes.io/managed-by: kustomize
  name: netboxippool-viewer-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - netboxippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - netboxippools/status
  verbs:
  - get
