# permissions for end users to edit netboxiprangepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-ipam-provider-netbox
    app.kubernetes.io/managed-by: kustomize
  name: netboxiprangepool-editor-role
rules:
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - netboxiprangepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.cluster.x-k8s.io
  resources:
  - netboxiprangepools/status
  verbs:
  - get
