apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-ipam-provider-netbox
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
