//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangeGlobalPool) DeepCopyInto(out *NetboxIPRangeGlobalPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangeGlobalPool.
func (in *NetboxIPRangeGlobalPool) DeepCopy() *NetboxIPRangeGlobalPool {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangeGlobalPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxIPRangeGlobalPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangeGlobalPoolList) DeepCopyInto(out *NetboxIPRangeGlobalPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetboxIPRangeGlobalPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangeGlobalPoolList.
func (in *NetboxIPRangeGlobalPoolList) DeepCopy() *NetboxIPRangeGlobalPoolList {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangeGlobalPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxIPRangeGlobalPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangeGlobalPoolSpec) DeepCopyInto(out *NetboxIPRangeGlobalPoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangeGlobalPoolSpec.
func (in *NetboxIPRangeGlobalPoolSpec) DeepCopy() *NetboxIPRangeGlobalPoolSpec {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangeGlobalPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangeGlobalPoolStatus) DeepCopyInto(out *NetboxIPRangeGlobalPoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new(NetboxPoolStatusIPAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangeGlobalPoolStatus.
func (in *NetboxIPRangeGlobalPoolStatus) DeepCopy() *NetboxIPRangeGlobalPoolStatus {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangeGlobalPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangePool) DeepCopyInto(out *NetboxIPRangePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangePool.
func (in *NetboxIPRangePool) DeepCopy() *NetboxIPRangePool {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxIPRangePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangePoolList) DeepCopyInto(out *NetboxIPRangePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetboxIPRangePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangePoolList.
func (in *NetboxIPRangePoolList) DeepCopy() *NetboxIPRangePoolList {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxIPRangePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangePoolSpec) DeepCopyInto(out *NetboxIPRangePoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangePoolSpec.
func (in *NetboxIPRangePoolSpec) DeepCopy() *NetboxIPRangePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxIPRangePoolStatus) DeepCopyInto(out *NetboxIPRangePoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new(NetboxPoolStatusIPAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxIPRangePoolStatus.
func (in *NetboxIPRangePoolStatus) DeepCopy() *NetboxIPRangePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NetboxIPRangePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPoolStatusIPAddresses) DeepCopyInto(out *NetboxPoolStatusIPAddresses) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPoolStatusIPAddresses.
func (in *NetboxPoolStatusIPAddresses) DeepCopy() *NetboxPoolStatusIPAddresses {
	if in == nil {
		return nil
	}
	out := new(NetboxPoolStatusIPAddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixGlobalPool) DeepCopyInto(out *NetboxPrefixGlobalPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixGlobalPool.
func (in *NetboxPrefixGlobalPool) DeepCopy() *NetboxPrefixGlobalPool {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixGlobalPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxPrefixGlobalPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixGlobalPoolList) DeepCopyInto(out *NetboxPrefixGlobalPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetboxPrefixGlobalPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixGlobalPoolList.
func (in *NetboxPrefixGlobalPoolList) DeepCopy() *NetboxPrefixGlobalPoolList {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixGlobalPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxPrefixGlobalPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixGlobalPoolSpec) DeepCopyInto(out *NetboxPrefixGlobalPoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixGlobalPoolSpec.
func (in *NetboxPrefixGlobalPoolSpec) DeepCopy() *NetboxPrefixGlobalPoolSpec {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixGlobalPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixGlobalPoolStatus) DeepCopyInto(out *NetboxPrefixGlobalPoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new(NetboxPoolStatusIPAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixGlobalPoolStatus.
func (in *NetboxPrefixGlobalPoolStatus) DeepCopy() *NetboxPrefixGlobalPoolStatus {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixGlobalPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixPool) DeepCopyInto(out *NetboxPrefixPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixPool.
func (in *NetboxPrefixPool) DeepCopy() *NetboxPrefixPool {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxPrefixPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixPoolList) DeepCopyInto(out *NetboxPrefixPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetboxPrefixPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixPoolList.
func (in *NetboxPrefixPoolList) DeepCopy() *NetboxPrefixPoolList {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetboxPrefixPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixPoolSpec) DeepCopyInto(out *NetboxPrefixPoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixPoolSpec.
func (in *NetboxPrefixPoolSpec) DeepCopy() *NetboxPrefixPoolSpec {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetboxPrefixPoolStatus) DeepCopyInto(out *NetboxPrefixPoolStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = new(NetboxPoolStatusIPAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetboxPrefixPoolStatus.
func (in *NetboxPrefixPoolStatus) DeepCopy() *NetboxPrefixPoolStatus {
	if in == nil {
		return nil
	}
	out := new(NetboxPrefixPoolStatus)
	in.DeepCopyInto(out)
	return out
}
