name: Create Container Image

on:
  push:
    branches:
      - main
      - release-*
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: write
  packages: write

jobs:
  main-image:
    name: build "main" image
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/erwin-kok/cluster-api-ipam-provider-netbox
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan image
        uses: anchore/scan-action@v4
        id: scan
        with:
          image: ${{ steps.meta.outputs.tags }}
          add-cpes-if-none: true
          output-format: table
