name: Create Draft Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Allow creating a release.

jobs:
  draft_release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Create Release Artifacts
        run: |
          make release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: out/*.*

  release_image:
    name: Build and Push Release Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Create Licenses Report
        run: |
          make licenses-report

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/erwin-kok/cluster-api-ipam-provider-netbox

      - name: Get Version Information
        id: version_info
        run: |
          echo "LDFLAGS=$(hack/version.sh)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ldflags=${{ steps.version_info.outputs.LDFLAGS }}
